# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd002ed212a0c4a44e0d2c53420abba6e2f44f84a4c47154c039c9cc643d3f9ab4edc0c003a6c23a9d7e82855b6c3a352b40d81d3bb2d2262ccaa21bc7effbee

test:
  secret_key_base: 79166e0b2a129b6c06fa4b5fedeb3d6fcb342e834b452ef2acd2cc8f92f149dedc039cf7306c34707874f89e403df560ad4fa6fa6dd3789f0e0b8c4bf000b37a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
